# .github/workflows/cicd.yml

name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # Checkout code from Github
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
       # Install dependencies, build and push docker image to DockerHub
            - name: Install dependencies
              run: npm install

            - name: Build React app
              run: npm run build
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push docker image
            - name: Docker Build and Push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile.prod
                  push: true
                  tags: issarapong/react-ci-cd:latest
        # Deploy to Cloud
            - name: Deploy to Cloud
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      docker pull issarapong/react-ci-cd:latest
                      docker stop react-ci-cd
                      docker rm react-ci-cd
                      docker run -d --name react-ci-cd -p 80:80 issarapong/react-ci-cd:latest